#ifndef _TETHER_RENDERING_VULKAN_COMMON_SHADERTYPE_HPP
#define _TETHER_RENDERING_VULKAN_COMMON_SHADERTYPE_HPP

namespace Tether::Rendering::Vulkan
{
	enum class ShaderType
	{
		VERTEX,
		GEOM, // ! CURRENTLY UNSUPPORTED
		COMPUTE, // ! CURRENTLY UNSUPPORTED
		FRAG
	};
}

#endif //_TETHER_RENDERING_VULKAN_COMMON_SHADERTYPE_HPP